### ISSUE TITLE
Strict mode violation error in google play

### ISSUE THREAD

**Issue by yfer** [AppsFlyerSDK/appsflyer-flutter-plugin#139]
**Describe the bug**
Google play shows: 
```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ldalvik/system/DexPathList;->nativeLibraryDirectories:Ljava/util/List;
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ldalvik/system/BaseDexClassLoader;->pathList:Ldalvik/system/DexPathList;
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ldalvik/system/DexPathList;->nativeLibraryPathElements:[Ldalvik/system/DexPathList$NativeLibraryElement;
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/app/ActivityThread;->currentApplication()Landroid/app/Application;
```

Details of one such exception: 

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ldalvik/system/BaseDexClassLoader;->pathList:Ldalvik/system/DexPathList;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at com.appsflyer.internal.b.<clinit>(:124)
	at com.appsflyer.internal.b.$$b(Unknown Source:0)
	at com.appsflyer.AppsFlyerLibCore$b.run(:36)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.appsflyer.AFExecutor$1$4.run(:2)
	at java.lang.Thread.run(Thread.java:764)
```

**To Reproduce**
1. Setup  appsflyer_sdk: ^6.2.4+4-nullsafety
2. build app
3. deploy it to google play, google play shows theese messages

**Expected behavior**
Expect appsflyer not to use non-sdk apis

**Comment by yfer** [comment]
@marslannasr7koncepts 
no i didn'tPlay store ignores it. 
Don't think this is apple-related, because java.
