### ISSUE TITLE
appsflyer_sdk: ^6.3.5+1 java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/localbroadcastmanager/content/LocalBroadcastManager;

### ISSUE THREAD

**Issue by josephmangmang** [AppsFlyerSDK/appsflyer-flutter-plugin#152]
Hi i cannot initialize the plugin. Sdk is throwing error:
Version:  appsflyer_sdk: ^6.3.5+1

```
E/AndroidRuntime( 1991): FATAL EXCEPTION: main
E/AndroidRuntime( 1991): Process: com.dmytroporoshyn.my_book_reloaded, PID: 1991
E/AndroidRuntime( 1991): java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/localbroadcastmanager/content/LocalBroadcastManager;
E/AndroidRuntime( 1991): 	at com.appsflyer.appsflyersdk.AppsFlyerStreamHandler.onListen(AppsFlyerStreamHandler.java:21)
E/AndroidRuntime( 1991): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:188)
E/AndroidRuntime( 1991): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:167)
E/AndroidRuntime( 1991): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime( 1991): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime( 1991): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 1991): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime( 1991): 	at android.os.Looper.loop(Looper.java:206)
E/AndroidRuntime( 1991): 	at android.app.ActivityThread.main(ActivityThread.java:8595)
E/AndroidRuntime( 1991): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1991): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime( 1991): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/AndroidRuntime( 1991): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.localbroadcastmanager.content.LocalBroadcastManager" on path: DexPathList[[zip file "/data/app/~~FaEDzDKWTOdivG-A7OnITw==/com.dmytroporoshyn.my_book_reloaded-XMrGoRG7soflOCC10wKe8Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~FaEDzDKWTOdivG-A7OnITw==/com.dmytroporoshyn.my_book_reloaded-XMrGoRG7soflOCC10wKe8Q==/lib/arm64, /data/app/~~FaEDzDKWTOdivG-A7OnITw==/com.dmytroporoshyn.my_book_reloaded-XMrGoRG7soflOCC10wKe8Q==/base.apk!/lib/arm64-v8a, /system/lib64]]
E/AndroidRuntime( 1991): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime( 1991): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 1991): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 1991): 	... 12 more
```

My temporary solution:

Manually add the dependency
```
dependencies {
    ...
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'
}
```

**Comment by pazlavi** [comment]
Hi @josephmangmang ,
Thank you for reaching out to us.

This is happening because of a deprecated method in our plugin. We will be sunset this method in the upcoming release.

**Comment by DFelten** [comment]
The same error appears on our apps. What's the current status of the fix?
