### ISSUE TITLE
Issue with enableFacebookDeferredApplinks(true);

### ISSUE THREAD

**Issue by gidrokolbaska** [AppsFlyerSDK/appsflyer-flutter-plugin#251]
**Describe the bug**
Hello!
Could you please explain whats the point in invoking enableFacebookDeferredApplinks(true)? The docs are really unclear about this. The only thing it says is that it should be invoked BEFORE initSdk(). However, it just throws a huge error stack in the console if done so:

```
D/AppsFlyer_6.9.3(22769): Initializing AppsFlyer SDK: (v6.9.3.223)
D/TrafficStats(22769): tagSocket(113) with statsTag=0x4e864ee, statsUid=-1
I/AppsFlyer_6.9.3(22769): Starting AppsFlyer: (v6.9.3.223)
I/AppsFlyer_6.9.3(22769): Build Number: 223
D/AppsFlyer_6.9.3(22769): QUEUE: tried to add already running task: RC_CDN-UpdateRemoteConfiguration-2
D/AppsFlyer_6.9.3(22769): QUEUE: new task added: LOAD_CACHE-LoadCachedRequests-3
I/AppsFlyer_6.9.3(22769): appsflyer_backup_rules.xml detected, using AppsFlyer defined backup rules for AppsFlyer SDK data
D/AppsFlyer_6.9.3(22769): QUEUE: starting task execution: LOAD_CACHE-LoadCachedRequests-3
D/AppsFlyer_6.9.3(22769): QUEUE: execution finished for LOAD_CACHE-LoadCachedRequests-3, result: SUCCESS
E/katestappsflyer(22769): Invalid ID 0x00000000.
E/MethodChannel#af-api(22769): Failed to handle method call
E/MethodChannel#af-api(22769): android.content.res.Resources$NotFoundException: String resource ID #0x0
E/MethodChannel#af-api(22769): 	at android.content.res.Resources.getText(Resources.java:453)
E/MethodChannel#af-api(22769): 	at android.content.res.Resources.getString(Resources.java:546)
E/MethodChannel#af-api(22769): 	at android.content.Context.getString(Context.java:762)
E/MethodChannel#af-api(22769): 	at com.appsflyer.internal.AFb1zSDK.afErrorLog(:23093)
E/MethodChannel#af-api(22769): 	at com.appsflyer.internal.AFb1zSDK.start(:971)
E/MethodChannel#af-api(22769): 	at com.appsflyer.internal.AFb1zSDK.start(:924)
E/MethodChannel#af-api(22769): 	at com.appsflyer.internal.AFb1zSDK.start(:919)
E/MethodChannel#af-api(22769): 	at com.appsflyer.appsflyersdk.AppsflyerSdkPlugin.initSdk(AppsflyerSdkPlugin.java:759)
E/MethodChannel#af-api(22769): 	at com.appsflyer.appsflyersdk.AppsflyerSdkPlugin.onMethodCall(AppsflyerSdkPlugin.java:203)
E/MethodChannel#af-api(22769): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#af-api(22769): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#af-api(22769): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#af-api(22769): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#af-api(22769): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#af-api(22769): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#af-api(22769): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#af-api(22769): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#af-api(22769): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/MethodChannel#af-api(22769): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#af-api(22769): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#af-api(22769): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
D/AppsFlyer_6.9.3(22769): InstallReferrer connected
E/flutter (22769): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, String resource ID #0x0, null, android.content.res.Resources$NotFoundException: String resource ID #0x0
E/flutter (22769): 	at android.content.res.Resources.getText(Resources.java:453)
E/flutter (22769): 	at android.content.res.Resources.getString(Resources.java:546)
E/flutter (22769): 	at android.content.Context.getString(Context.java:762)
E/flutter (22769): 	at com.appsflyer.internal.AFb1zSDK.afErrorLog(:23093)
E/flutter (22769): 	at com.appsflyer.internal.AFb1zSDK.start(:971)
E/flutter (22769): 	at com.appsflyer.internal.AFb1zSDK.start(:924)
E/flutter (22769): 	at com.appsflyer.internal.AFb1zSDK.start(:919)
E/flutter (22769): 	at com.appsflyer.appsflyersdk.AppsflyerSdkPlugin.initSdk(AppsflyerSdkPlugin.java:759)
E/flutter (22769): 	at com.appsflyer.appsflyersdk.AppsflyerSdkPlugin.onMethodCall(AppsflyerSdkPlugin.java:203)
E/flutter (22769): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (22769): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (22769): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (22769): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (22769): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (22769): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (22769): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (22769): 	at android.os.Looper.loop(Looper.java:288)
E/flutter (22769): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/flutter (22769): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (22769): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (22769): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter (22769): )
```

**Smartphone (please complete the following information):**
 - Device: Android Emulator
 - OS: Android 13

**Comment by gidrokolbaska** [comment]
nvm, fixed it myself
