### ISSUE TITLE
No default values for parameters of initSdk

### ISSUE THREAD

**Issue by minusminuszero** [AppsFlyerSDK/appsflyer-flutter-plugin#29]
Input params for initSdk are optional, however they don't have default values and are not checked for null. Omitting either of them results in the below exception. I'm not sure if there are any further repercussions as the result of that exception. 
This happens on the latest version of the plugin: 5.2.0+1.

```
E/flutter (32469): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Failed assertion: boolean expression must not be null
E/flutter (32469): #0      AppsflyerSdk.initSdk.<anonymous closure> (package:appsflyer_sdk/src/appsflyer_sdk.dart:147:11)
E/flutter (32469): #1      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (32469): #2      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (32469): #3      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
E/flutter (32469): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (32469): #5      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (32469): #6      Future._complete (dart:async/future_impl.dart:516:7)
E/flutter (32469): #7      new Future.delayed.<anonymous closure> (dart:async/future.dart:313:16)
E/flutter (32469): #8      _rootRun (dart:async/zone.dart:1122:38)
E/flutter (32469): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (32469): #10     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (32469): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter (32469): #12     _rootRun (dart:async/zone.dart:1126:13)
E/flutter (32469): #13     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (32469): #14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
E/flutter (32469): #15     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (32469): #16     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (32469): #17     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (32469): #18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (32469):
```

**Comment by af-fess** [comment]
Thank you @minusminuszero we will check it out
