### ISSUE TITLE
exp.hasMatch(appID)': is not true.

### ISSUE THREAD

**Issue by bugrevealingbme** [AppsFlyerSDK/appsflyer-flutter-plugin#303]
I can't launch my app because of this error.

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:appsflyer_sdk/src/appsflyer_sdk.dart': Failed assertion: line 83 pos 14: 'exp.hasMatch(appID)': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      AppsflyerSdk._validateAFOptions (package:appsflyer_sdk/src/appsflyer_sdk.dart:83:14)
#3      AppsflyerSdk.initSdk.<anonymous closure> (package:appsflyer_sdk/src/appsflyer_sdk.dart:162:28)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:846:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:875:13)
#6      Future._complete (dart:async/future_impl.dart:638:7)
#7      new Future.delayed.<anonymous closure> (dart:async/future.dart:424:16)
#8      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)

**Comment by bugrevealingbme** [comment]
In iOS, this problem happens when you start the app id with "id". The documentation is not clear enough.
