### ISSUE TITLE
The app crashes due to NullPointerException

### ISSUE THREAD

**Issue by artyom-frolov** [AppsFlyerSDK/appsflyer-flutter-plugin#329]
**Describe the bug**
After integrating the AppsFlyer SDK into our Flutter app, some Android users experience crashes. No special actions are required from the user to reproduce the bug. This issue is similar to #322 but our app doesn't use deeplinks and has a different call stack.

Callstack:
```
Exception java.lang.NullPointerException:
  at com.appsflyer.appsflyersdk.AppsflyerSdkPlugin$5$1.run (AppsflyerSdkPlugin.java:384)
  at android.os.Handler.handleCallback (Handler.java:914)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:224)
  at android.app.ActivityThread.main (ActivityThread.java:7551)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:995)
```

**To Reproduce**
We cannot identify specific reproducible steps; the issue occurs unexpectedly.

**Expected behavior**
The app should work without crashes.

**Screenshots**
Callstack from Sentry:

![Sentry](https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/assets/135605890/ecafd981-4b90-439a-9228-a25a964460ea)

**Smartphone:**
 - Device: Redmi begonia (Redmi Note 8 Pro)
 - OS: Android 11 (SDK 30)

**Additional context**
AppsFlyer SDK version: 6.13.2+1
Flutter version: 3.13.9 (stable)
Engine revision 0545f8705d
Dart version: 3.1.5
DevTools version: 2.25.0
IDE: VS Code (version 1.90.2)

**Comment by Nirvana-cn** [comment]
the same problem.

**Comment by MahendraN35** [comment]
We are facing the same problem too and we are using `appsflyer_sdk (6.14.3)`.

**Comment by RonyBrosh** [comment]
As a quick fix we reverted our AppsFlyer version update back to **6.13.0+1**.
We never had those crashes with that version but keep in mind that deferred deep links won't work for you on iOS with that version of AppsFlyer. They will on Android though.

**Comment by artyom-frolov** [comment]
I conacted with support. Their response:
"I discussed this issue the mobile team and based on the error trace and shared code snippet It seems like we have an issue with the new startSDK method with onSuccess and onError callbacks [here](https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/blob/v6.13.2/android/src/main/java/com/appsflyer/appsflyersdk/AppsflyerSdkPlugin.java#L384). As a workaround, we can suggest removing the callbacks on the Flutter side if they are not in use in your app logic and using [startSDK](https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/blob/v6.13.2/doc/API.md#-startsdk-added-in-6130) without the callback."

I'll try this workaround. Maybe it will help someone too.

**Comment by wiktoriasobczyk** [comment]
Release of new package version should resolve this problem https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/releases/tag/v6.15.2

**Comment by JuliaIncibit** [comment]
I think this is related:
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void D8.r.a(java.lang.String, java.lang.Object, D8.q)' on a null object reference
       at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:102)
       at com.appsflyer.appsflyersdk.AppsflyerSdkPlugin$5.lambda$onSuccess$0(AppsflyerSdkPlugin.java:389)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8097)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
Using appslyer 6.15.2, reported on Crashlytics (Redmi 10A Android 11)

**Comment by jiagengArctuition** [comment]
We are facing the same problem too and we are using   appsflyer_sdk: 6.16.2
